spring:
  h2:
    console:
      enabled: true
      patch: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inyestar_db;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB