auth:
  rest-api:
    kakao:
      host: https://dapi.kakao.com
      key: a055f65863636837f870f19987630e08
    naver:
      host: https://openapi.naver.com
      client-id: VgT84vVPLVsakiLf4IZu
      client-secret: E1fmr8TUk6
